SesacProjectTeamC/SesacIn

views/components/cdn.ejs
views/styles/globalstyle.css

feat: 공용 컴포넌트 및 스타일 생성

---

.gitignore
app.js
package.json
routes/index.js

description: api관리를 위해 스웨거를 추가함

refactor: swagger 코드 추가

---

.gitignore
api.http
config/config.json
controller/Canswer.js
controller/Cboard.js
controller/Ccomment.js
controller/Cpage.js
controller/Cuser.js
routes/index.js

descriptions:
회원가입, 정보 조회, 정보 수정, 회원탈퇴 기능 추가

feat: 사용자 관련 기능 추가

---

app.js
controller/Cboard.js
routes/boardRouter.js
routes/index.js

refactor: board 라우터로 이동 코드 추가
feat: 자유게시판 관련 라우터 구조 추가
feat: board 컨트롤러 추가

Board page api 11

---

views/login.ejs
views/styles/globalstyle.css
views/styles/login.css

description: form 완성 css적용 완료 >> 채림님 코드가 없어져서 일부 업로드

feat: login.ejs 완성

---

controller/Cboard.js
routes/boardRouter.js
views/boardDetailTestTgkim.ejs
views/boardTestTgkim.ejs

description:
1. 게시글 생성 처리 / 게시글의 댓글 생성처리 로그인 검사
요청 데이터 Null 검사
부적절한 단어 검사 (라이브러리만 찾아봄)
시퀄라이저 db 작업시 에러처리
모든 응답에 status 추가
2. 테스트용 ejs 파일 생성 
- 자유게시판 게시글 각각의 상세페이지를 만들고 댓글 생성 테스트(boardDetailTestTgkim) 
+ 프론트에서 axios요청시 백엔드로부터 받은 에러에 대해 catch로 에러처리도 해봤음
- 자유게시판 새 게시글 생성하기 페이지를 만들고 게시글 생성 테스트(boardTestTgkim) 
+ 프론트에서 axios요청시 백엔드로부터 받은 에러에 대해 catch로 에러처리도 해봤음

refactor: 자유게시판 게시글/댓글 생성 오류처리 테스트

---

controller/Cboard.js
models/User.js
routes/boardRouter.js

description:
- board/:bId : 자유게시판 개별 게시글 상세페이지 렌더
- /board/create : 자유게시판 새 게시물 생성페이지 렌더

refactor: board api 수정

---

controller/Cboard.js
controller/Cquestion.js
routes/questionRouter.js
static/js/index.js

Board, Question
페이징 처리 api 리팩토링(createAt 데이터 포맷 변경후 응답값으로 전송)

BoardQuestionApi-76

---

controller/Cboard.js
routes/boardRouter.js
views/boardDetailTest.ejs
views/boardEditTest.ejs

description:
- 자유게시판 게시글 상세 페이지에 게시글 수정/삭제
- 프론트 코드 : 테스트용 코드 작성
- 백엔드 코드 : 기능 코드 작성 / 테스트
- 자유게시판 게시글 수정 페이지
- 프론트 : 테스트용 코드 작성
- 백엔드 : 수정내용 저장하기 기능 코드 작성 / 테스트

feat: 자유게시판 게시글 수정/ 수정하기 페이지

---

controller/CmyPage.js
controller/Cquestion.js
routes/index.js
views/components/header.ejs
views/components/questionBoardCard copy.ejs
views/components/testCard.ejs
views/myPage.ejs

description: 
1) 조회수 기능 구현
2) 마이페이지
(1) 좋아요 히스토리(질문, 답변) 리스트 조회
(2) 작성한 게시글(질문, 답변, 댓글) 리스트 조회 
- test용 파일 생성 : Cmypage.js, myPage.ejs, header에 마이페이지 a 태그, test(Q/A/C)Card 
- 팀원들과 조율 후 수정하겠습니다.

feat: myPage 히스토리 확인, 조회수 기능 구현

---

app.js
controller/Cboard.js
controller/Cprofile.js
controller/Cuser.js
routes/index.js
views/components/header.ejs
views/editprofile.ejs
views/join.ejs
views/login.ejs
views/styles/register.css

<수정 내용>
1. 아이디/닉네임에 중복여부 확인 처리 추가 (화면+기능)
2. 비밀번호 * 처리
3. 새싹 크루입니까에 아니오 체크시 새싹 캠퍼스 선택 없도록
4. 가입하기 버튼에서 유효성검사 (비밀번호 유효성 검사를 실패했는데 ID 유효성 검사에 대한 내용이 나오는 오류 수정)
5. 회원가입 페이지랑 로그인 페이지 뒤로가기 버튼 → 사용자가 전에 머물렀던 페이지로 이동하게 변경

Register 87

---

app.js
controller/Cboard.js
controller/Cquestion.js
static/js/index.js

description:
자유게시판 페이지렌더링 컨트롤러에서 세션처리
페이지별 호출시 응답값 변경 : {boards: 페이징 처리된 게시글 데이터,
pageCount: 총 페이지 수,
cDate: 포맷 변경된 createAt 데이터,
msg: 처리완료 메세지,
}

refactor: 자유게시판 관련 페이지 렌더링 컨트롤러에서 세션 처리

---

controller/Cboard.js
routes/boardRouter.js

- 자유게시판 관련 페이지 세션처리 
- 게시글 작성 페이지 호출시 생성일 데이터 포맷 변경값으로 응답
- 댓글 관련 응답값 수정/세션 수정

자유게시판 관련 세션 처리 / 응답값 수정

---

app.js
swagger.js
swaggerDefinition.json

description:
- ./swagger.js : 스웨거 모듈
- ./swaggerDefinition.json : 스웨거에 표시될 API 정의 파일

refactor: swagger 코드 모델로 분리

---

app.js
swagger.js
swaggerDefinition.json

env 라이브러리 추가

---

app.js
controller/Cupload.js
multerConfig.js
package.json
routes/uploadRouter.js
swagger.js
swaggerDefinition.json

- multer 라이브러리 추가
- upload 라우터 추가
- Cupload 컨트롤러 추가 : 이미지 업로드 API 추가 (POST)"

feat: 이미지 업로드 API 추가

---

views/components/header.ejs
views/join.ejs
views/login.ejs
views/profile.ejs
views/styles/globalstyle.css
views/styles/register.css

<회원가입 페이지>
- 헤더에서 회원가입 제외
- 회원가입 h1태그 사이즈 수정
- 입력값들에 대해 onInput으로 밑에 유효성 조건 띄워주고 맞으면 사라짐 + 중복 확인 버튼 활성화
- 중복 확인 결과는 밑에 바로 띄워주고 다른 곳 클릭 시 사라짐
<로그인 페이지>
- 로그인페이지에서 비밀번호 처리시 * 으로 표기
- 뒤로가기 버튼 클릭시 홈으로 이동

refactor: 회원가입 유효성 검사 및 중복 검사 에러 메세지 수정

---

controller/Cprofile.js
routes/usersRouter.js

description:
- 세션 삭제처리 확인
- 성공시 프론트엔드에서 메인페이지로 리다이렉트 하도록 되어 있음

refactor: 회원탈퇴시 세션 삭제처리

---

controller/Cuser.js

description:
- 로직 추가 및 response 데이터 정의

refactor: 회원가입 처리시 중복검사 로직 추가

---

controller/Cboard.js
controller/Cquestion.js
routes/boardRouter.js
routes/questionRouter.js
static/js/main.js
views/components/freeBoardCard.ejs
views/components/header.ejs
views/components/questionBoardCard.ejs
views/listMain.ejs
views/main.ejs

메인스크린 데이터 연동

---

app.js
controller/Cboard.js
routes/boardRouter.js
views/mainTest.ejs

description:
최신순 / createAt / DESC 오랜순 / createAt / ASC
좋아요 많은 순 / likeCount / DESC
좋아요 적은 순 / likeCount / ASC
조회수 많은 순 / viewCount / DESC
조회수 적은 순 / viewCount / ASC
댓글 많은 순 / commentCount /  DESC
댓글 적은 순 / commentCount /  ASC

feat: 자유게시판 게시글 sort

---

app.js
models/User.js
views/editprofile.ejs
views/login.ejs
views/profileTestImg.ejs
views/styles/login.css

- db user 테이블 이미지 관련 기본값 수정
- 헤더 수정
- 회원 정보 수정 완료 시 마이페이지로 리다이렉트

refactor: 헤더, 회원정보, 수정 페이지 수정

---

controller/Canswer.js
controller/Cquestion.js
static/js/index.js
views/questionTest.ejs

description:
1) 로그인 했을 경우에만 질문 및 답변 좋아요, 답변 및 댓글 등록 가능
2) 작성자 일치했을 경우에만 수정 및 삭제 버튼 보임

feat: 로그인, 로그아웃 시 질문 게시판 수정

---

.gitignore

description: 유저가 업로드한 이미지 파일 gitignore 에 추가

refactor: Update gitignore

---

.gitignore

refactor: gitignore 업데이트

---

static/js/boardDetail.js
static/js/questionDetail.js
views/community/boardDetail.ejs
views/community/listMain.ejs
views/community/questionDetail.ejs
views/styles/boardDetail.css
views/styles/index.css
views/styles/listMain.css

fix: 메인, 리스트, 상세 스크린 반응형
